"""Rocket-system performance equations and propellant reference data."""

from .burns import (
    BurnDefinition,
    BurnResult,
    BurnTarget,
    BurnTargetKind,
    ConstantBurnReduction,
    ConstantPerformanceProvider,
    EngineOperatingPoint,
    FlowDestination,
    ProfiledBurnPoint,
    ProfiledBurnResult,
    ProfiledPerformanceProvider,
    PropellantFlow,
    PropellantRole,
    PropulsionProvider,
    TankDefinition,
    ThrottleSchedule,
    ThrottleSegment,
    build_burn_html_report,
    burn_result_from_dict,
    burn_result_from_json,
    burn_result_to_dict,
    burn_result_to_json,
    reduce_to_constant,
    simulate_burn,
    simulate_constant_burn,
    simulate_profiled_burn,
)
from .cycles import EngineCycleResult, calculate_engine_cycle
from .losses import LossTerm, PerformanceLossBudget, calculate_loss_budget
from .performance import (
    STANDARD_GRAVITY_M_S2,
    RocketEquationResult,
    ThrustResult,
    calculate_rocket_equation,
    calculate_thrust,
)
from .propellants import PROPELLANTS, PropellantRecord, list_propellants
from .staging import (
    StageDefinition,
    StageSolution,
    StagingOptimizationResult,
    optimize_staging,
)
from .two_phase import TwoPhasePerformanceBand, calculate_two_phase_band

__all__ = [
    "PROPELLANTS",
    "STANDARD_GRAVITY_M_S2",
    "BurnDefinition",
    "BurnResult",
    "BurnTarget",
    "BurnTargetKind",
    "ConstantBurnReduction",
    "ConstantPerformanceProvider",
    "EngineCycleResult",
    "EngineOperatingPoint",
    "FlowDestination",
    "LossTerm",
    "PerformanceLossBudget",
    "ProfiledBurnPoint",
    "ProfiledBurnResult",
    "ProfiledPerformanceProvider",
    "PropellantFlow",
    "PropellantRecord",
    "PropellantRole",
    "PropulsionProvider",
    "RocketEquationResult",
    "StageDefinition",
    "StageSolution",
    "StagingOptimizationResult",
    "TankDefinition",
    "ThrottleSchedule",
    "ThrottleSegment",
    "ThrustResult",
    "TwoPhasePerformanceBand",
    "build_burn_html_report",
    "burn_result_from_dict",
    "burn_result_from_json",
    "burn_result_to_dict",
    "burn_result_to_json",
    "calculate_engine_cycle",
    "calculate_loss_budget",
    "calculate_rocket_equation",
    "calculate_thrust",
    "calculate_two_phase_band",
    "list_propellants",
    "optimize_staging",
    "reduce_to_constant",
    "simulate_burn",
    "simulate_constant_burn",
    "simulate_profiled_burn",
]
